apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d71vk8nz9-python 
  janus-idp.io/tekton: d71vk8nz9-python
  backstage.io/kubernetes-id: d71vk8nz9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d71vk8nz9-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  